export interface FeatureFlagDefinition {
  key: string;
  label: string;
  description: string;
  channel: 'stable' | 'experimental';
  defaultEnabled: boolean;
}

export const FLAG_RENAME_MAP: Record<string, string> = {
  'lineup_filters_enabled': 'lineups_filters_enabled',
  'drought_enhancements': 'droughts_enhancements_enabled',
  'run_creation_index': 'runs_creation_index_enabled',
  'threshold_trigger_record': 'analytics_threshold_trigger_record_enabled',
  'context_shot_diet': 'analytics_context_shot_diet_enabled',
  'matchup_intelligence': 'analytics_matchup_intelligence_enabled',
  'live_scoreboard': 'games_live_scoreboard_enabled',
  'shot_chart': 'shots_chart_enabled',
  'analytics_lab': 'analytics_lab_enabled',
  'debug_panel': 'games_debug_panel_enabled',
};

export const FEATURE_FLAGS: FeatureFlagDefinition[] = [
  {
    key: 'lineups_filters_enabled',
    label: 'Lineup Filter Controls',
    description: 'Show sort and filter controls on the Lineups subtab (min minutes, net rating threshold, leverage filter)',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'lineups_player_filters_enabled',
    label: 'Lineup Player Filters',
    description: 'Filter lineup segments by players on the court (1-5 players) with bottom sheet selector',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'lineups_on_court_summary_enabled',
    label: 'On-Court Summary',
    description: 'Show aggregated performance summary when filtering lineups by players',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'lineups_on_court_summary_details_enabled',
    label: 'On-Court Summary Details',
    description: 'Tap the On-Court Summary to view detailed shooting, turnovers, rebounding, and opponent stats for the selected on-court interval',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'lineups_on_court_summary_context_enabled',
    label: 'On-Court Summary Game Flow Context',
    description: 'Show how many runs and droughts overlap with the selected on-court interval in the detail view',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'lineups_on_court_summary_on_off_enabled',
    label: 'On-Court Summary On/Off Rating',
    description: 'Show On/Off Rating split comparing team performance when selected players are on vs off the court',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'lineups_deep_dive_enabled',
    label: 'Lineup Deep Dive',
    description: 'Tap a lineup segment to view detailed breakdown with stint-level data',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'droughts_enhancements_enabled',
    label: 'Drought Enhancements',
    description: 'Extended drought analytics with player-level impact scoring',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'droughts_lineup_context_enabled',
    label: 'Drought Lineup Context',
    description: 'Show the primary 5-man lineup on-court during each drought with substitution count indicator',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'droughts_end_event_caption_enabled',
    label: 'Drought Ending Event',
    description: 'Show a caption describing how each scoring drought ends',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'droughts_lineup_changes_enabled',
    label: 'Drought Lineup Phases',
    description: 'Allow expanding drought cards to see lineup phases and substitution timeline',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'runs_creation_index_enabled',
    label: 'Run Creation Index',
    description: 'Derived metric combining scoring, assists, stops, and lineup context during runs',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'analytics_threshold_trigger_record_enabled',
    label: 'Threshold Trigger Record',
    description: 'Team record when a chosen stat crosses a chosen band',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'analytics_context_shot_diet_enabled',
    label: 'Context Shot Diet Shift',
    description: 'Shot distribution changes in clutch vs non-clutch scenarios',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'analytics_matchup_intelligence_enabled',
    label: 'Matchup Intelligence',
    description: 'Head-to-head matchup comparison layer on the Game Page',
    channel: 'stable',
    defaultEnabled: true,
  },
  {
    key: 'games_live_scoreboard_enabled',
    label: 'Live Scoreboard',
    description: 'Real-time scoreboard from NBA CDN endpoints',
    channel: 'stable',
    defaultEnabled: true,
  },
  {
    key: 'shots_chart_enabled',
    label: 'Shot Chart',
    description: 'Visual shot chart on the Game Page',
    channel: 'stable',
    defaultEnabled: true,
  },
  {
    key: 'analytics_lab_enabled',
    label: 'Analytics Lab',
    description: 'Custom analytics lab with derived metrics',
    channel: 'stable',
    defaultEnabled: true,
  },
  {
    key: 'games_debug_panel_enabled',
    label: 'Debug Panel',
    description: 'Show debug diagnostics on the Games screen',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'games_source_badges_enabled',
    label: 'Games Source Badges',
    description: 'Show developer-only data-source badges such as LIVE DATA and FALLBACK on the Games scoreboard.',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'enablePlayoffBracketV1',
    label: 'Playoff Bracket V1',
    description: 'Show a Phase 1 Playoff Bracket entry point and mobile playoff tree built from existing NBA schedule metadata.',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'player_performance_screen_enabled',
    label: 'Player Performance Screen',
    description: 'Tap a player row in the box score to view individual player performance breakdown',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'shotquery_dev_view_enabled',
    label: 'ShotQuery Dev View',
    description: 'Developer validation surface for the ShotQuery engine showing normalized shot counts and filter results',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'shots_facilitator_filter_enabled',
    label: 'Facilitator Filter',
    description: 'Filter shots by the assisting player (facilitator) on the Shots tab',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'shots_detail_on_tap_enabled',
    label: 'Shot Detail on Tap',
    description: 'Tap a shot marker on the chart to view detailed shot information',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'shots_free_throws_enabled',
    label: 'Free Throws in Shots',
    description: 'Include Free Throws in the Shots tab scoring-opportunity model (FT, PPO, TS%, FT zone card, FT badge, FT-focused player pivot)',
    channel: 'experimental',
    defaultEnabled: true,
  },
  {
    key: 'shots_detail_navigation_enabled',
    label: 'Shot Detail Navigation',
    description: 'Navigate through filtered shots with previous/next controls in the shot detail sheet',
    channel: 'experimental',
    defaultEnabled: true,
  },
  {
    key: 'enableShotChartCourtGeometryV2',
    label: 'Shot Chart Court Geometry V2',
    description: 'Use refreshed basketball-correct half-court geometry for the Shots screen chart while preserving legacy rendering behind the flag.',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'stretches_unified_card_enabled',
    label: 'Unified Runs/Droughts Card',
    description: 'Render Runs and Droughts using the unified StretchCard with primary lineup and phases',
    channel: 'experimental',
    defaultEnabled: true,
  },
  {
    key: 'stretches_context_stats_enabled',
    label: 'Stretches Context Stats',
    description: 'Show PPO, A/TO, and play-finishing share on Run and Drought cards',
    channel: 'experimental',
    defaultEnabled: true,
  },
  {
    key: 'games_date_rail_enabled',
    label: 'Games Date Rail',
    description: 'Browse games by date using a horizontal date rail on the Games home (replaces Today / Recent / All scoreboard)',
    channel: 'experimental',
    defaultEnabled: true,
  },
  {
    key: 'games_calendar_modal_enabled',
    label: 'Games Calendar Modal',
    description: 'Open a month calendar modal from the Games home to jump to distant dates; stays in sync with the date rail and scoreboard selected date',
    channel: 'experimental',
    defaultEnabled: true,
  },
  {
    key: 'stretches_phase_events_enabled',
    label: 'Stretches Phase Events Sheet',
    description: 'Tap a lineup phase on a Run or Drought card to open a curated phase events sheet',
    channel: 'experimental',
    defaultEnabled: true,
  },
  {
    key: 'matchup_screen_real_data_enabled',
    label: 'Matchup Screen (Real Data)',
    description: 'Replace the legacy mock Matchup tab with a real-data Matchup foundation built from the selected game\'s box score and team stats.',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'shots_event_links_enabled',
    label: 'Shot Event Links',
    description: 'Tap the play description in the shot detail sheet to open the NBA.com event page in an in-app browser when a URL is available',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'enableMetricValidationDebug',
    label: 'Metric Validation Debug Panel',
    description: 'Show a developer-only debug panel inside the On-Court Detail sheet exposing raw ON/OFF metric values, confidence, and likely issues. Internal use only.',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'enableOnCourtSampleLabels',
    label: 'On-Court Possession Sample Labels',
    description: 'Show subtle ON/OFF possession sample sizes near the On/Off section of the On-Court Detail sheet.',
    channel: 'experimental',
    defaultEnabled: true,
  },
  {
    key: 'enableMetricConfidenceLabels',
    label: 'On-Court Confidence Labels',
    description: 'When the OFF-court sample is small, show a subtle "Small sample \u2014 interpret cautiously" label in the On-Court Detail sheet.',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'enableStatTraceDebug',
    label: 'Stat Trace Debug Panel',
    description: 'Show a developer-only Stat Trace panel inside the On-Court Detail sheet exposing each derived stat\'s formula, inputs, computed value, and confidence. Internal use only.',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'enableStatTraceWarnings',
    label: 'Stat Trace Drift Warnings',
    description: 'When the Stat Trace debug panel is enabled, show a subtle warning if a stat\'s displayed value differs from its formula-computed value beyond tolerance.',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'enableExternalPbpStatsValidation',
    label: 'External PBPStats Validation (Debug)',
    description: 'Developer-only: when On-Court Detail is open, fetch PBPStats on/off data for the selected player and show a CourtPulse vs PBPStats comparison panel. Disabled by default. No PBPStats network calls happen unless this is enabled.',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'enablePossessionAuditDebug',
    label: 'Possession Audit (Debug)',
    description: 'Developer-only: adds an "Open Possession Audit" entry inside the On-Court Detail External Validation panel. Opens a separate sheet that audits CourtPulse offensive/defensive possessions against PBPStats benchmarks. Internal use only.',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'enablePbpFiltersV1',
    label: 'PBP Filters V1',
    description: 'Feature-flagged revamped Game Detail play-by-play screen with mobile filter chips, player/event filters, clutch tagging, and live-game newest-first sorting.',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'enableDerivedContextTags',
    label: 'Derived PBP Context Tags',
    description: 'Show CourtPulse-derived context tags on play-by-play events, such as Off Turnover and explicit NBA fast-break qualifiers, without changing official event categories.',
    channel: 'experimental',
    defaultEnabled: false,
  },
  {
    key: 'feedback_reporting_enabled',
    label: 'In-App Feedback',
    description: 'Show in-app feedback and bug reporting entry points. Submissions include auto-captured app context and post to the configured feedback webhook.',
    channel: 'experimental',
    defaultEnabled: true,
  },
] as const;

export type FeatureFlagKey = typeof FEATURE_FLAGS[number]['key'];

export const FLAG_KEYS = FEATURE_FLAGS.map(f => f.key);
